### ISSUE TITLE
T4 customizations and tips

### ISSUE THREAD

**Issue by ErikEJ** [ErikEJ/EFCorePowerTools#1499]
- [x] Enum support [sample here](https://github.com/ErikEJ/EFCorePowerTools/issues/1472#issuecomment-1220273164)
- [x]  Custom collection initializers - see https://github.com/dotnet/efcore/issues/14249 and proposal: https://github.com/ErikEJ/EFCorePowerTools/issues/1499#issuecomment-1773937177
- [x] Custom collection types: https://github.com/dotnet/EntityFramework.Docs/blob/main/entity-framework/core/managing-schemas/scaffolding/templates.md#customize-the-entity-types 
- [x] restore collection setter (N/A - fixed in EF Core)
- [x] Pure POCO classes (new POCO template added)
- [x] Multiple sets of files generated (built-in, see the wiki docs)
- [x] [sharing same template across multiple projects](https://github.com/dotnet/EntityFramework.Docs/issues/4292#issuecomment-1475204600)
- [x] [Adding Obsolete attribute to some columns](https://github.com/ErikEJ/EFCorePowerTools/issues/1750#issuecomment-1482712950)
- [x] [Fix bad mappings](https://github.com/ErikEJ/EFCorePowerTools/issues/1930)
- [x] Property renaming
- [x] [Navigation comment](https://github.com/ErikEJ/EFCorePowerTools/issues/2367)
- [ ] INotifyPropertyChanged properties
- [ ] dbcontext splitting https://github.com/dotnet/EntityFramework.Docs/pull/3995#pullrequestreview-1083179761 https://github.com/dotnet/EntityFramework.Docs/blob/main/entity-framework/core/managing-schemas/scaffolding/templates.md#entity-configuration-classes https://github.com/dotnet/EntityFramework.Docs/pull/3995 https://github.com/R4ND3LL/EntityFrameworkRuler/blob/main/src/EntityFrameworkRuler.Design/Resources/EntityTypeConfiguration.t4
- [ ] Remove default constraints

[My dotnetConf video](https://learn.microsoft.com/en-us/events/dotnetconf-2022/t4-goodness-with-entity-framework-core-7)

**Comment by ErikEJ** [comment]
[Debugging templates](https://github.com/ErikEJ/EFCorePowerTools/issues/1557#issuecomment-1293514907)

**Comment by sonnemaf** [comment]
I love the new T4 templates. I have used it to create C# 11 required properties. 

This is my line 104 of the `EntityType.t4`
```cs
public <#= needsInitializer ? "required " : "" #><#= code.Reference(property.ClrType) #><#= needsNullable ? "?" : "" #> <#= property.Name #> { get; set; }
```

![image](https://user-images.githubusercontent.com/9335559/205306909-cbee82e5-a20f-461d-a6cc-49f74ece4cc3.png)

This generates this code if you use the `Northwind` sample database. The ProductName property is now `required`.

![image](https://user-images.githubusercontent.com/9335559/205306949-cc891448-8875-435f-8d56-21a3ceb13af8.png)

Thanks for your great work!

Fons

**Comment by ErikEJ** [comment]
@sonnemaf Great suggestion!

**Comment by mrunks** [comment]
Would there be a way to support any T4 file that is dropped into the templates folder rather than just the specific named three that are used for scaffolding out of the box. For example I could make one called Services.T4, or Controllers.T4, Views.TF etc.   My work around now is to create that code then rename them upon running the PowerTools.

**Comment by ErikEJ** [comment]
@mrunks not possible. But a setting to specify the location of the folder structure is very possible. Maybe create a separate issue and I will investigate.

**Comment by mrunks** [comment]
I am not clear how a different folder structure would help. I just want to be able to read additional files. Or are you suggesting having multiple folders all with the same file names and then it would iterate through each of the folders ?

**Comment by ErikEJ** [comment]
@mrunks I suggest you create a new issue and explain your exact requirements

**Comment by mrunks** [comment]
@ErikEJ I uninstalled a previous daily build that was used to test traversing other codetemplates folders and installed the latest version using visual studio  (2.5.1234).  I noticed the traversing other codetemplate directories is not working.   Is that feature not included in version 2.5.1234 ?

**Comment by ErikEJ** [comment]
@mrunks It should be...

**Comment by mrunks** [comment]
Something must have changed over the past few days as the feature is no longer working. I have tried uninstalling and reinstalling the latest extension.  And have the following Two folder structures in place

CodeTemplates
       EFCore
             DbContext.T4

Process
      CodeTemplates
              EFCore
                  EntityType.T4

Last Thursday the extension would pick up EntityType.T4 under the process folder and generate code but after installing version 2.5.1234  code is not being generated from the EntityType.T4 under the Processs path.  Is there something else that might have caused it to stop. I updated visual studio but then tried to reinstall the extension with no luck.

**Comment by ErikEJ** [comment]
I will have a look...

**Comment by KayakFisher205** [comment]
Is it possible to add the DisplayName Attribute in the T4 template? I've did a search but I've not see where anyone asked this or seen it implemented.

**[Display(Name= "Price")]**
public decimal? ListPrice {get; set;}

**Comment by ErikEJ** [comment]
@KayakFisher205  Where would the value for Name in Display come from?

**Comment by KayakFisher205** [comment]
Could it be from the Extended Properties, with the Name =FieldName and Value=the Display Name?
![image](https://user-images.githubusercontent.com/71768711/218524894-08f95925-4c23-4951-9fb5-138f4c275898.png)

**Comment by ErikEJ** [comment]
It could be the comment from the model, yes. I will provide an example later.

**Comment by ErikEJ** [comment]
@KayakFisher205 Just have a look at how "comments" are currently applied in the templates.

**Comment by AchrWasUnavailable** [comment]
When there is an error in the T4, the reverse engineering produces a general error message in the output window which makes it hard to find the root cause. Would it be possible to produce clear error messages like the output of a tt file > Run custom tool?

**E.g. output reverse engineer:**
`System.InvalidOperationException: Reverse engineer error: 
Microsoft.EntityFrameworkCore.Design.OperationException: Processing 'C:\Development\Playground\OEFS.Test\OEFS.Test.Data\OEFS.Test.Data\CodeTemplates\EFCore\DbContext.t4' failed.
   at void Microsoft.EntityFrameworkCore.Scaffolding.Internal.TextTemplatingModelGenerator.HandleErrors(TextTemplatingEngineHost host)
   at ScaffoldedModel Microsoft.EntityFrameworkCore.Scaffolding.Internal.TextTemplatingModelGenerator.GenerateModel(IModel model, ModelCodeGenerationOptions options)
   at ScaffoldedModel RevEng.Core.ReverseEngineerScaffolder.ScaffoldModel(string connectionString, DatabaseModelFactoryOptions databaseOptions, ModelReverseEngineerOptions modelOptions, ModelCodeGenerationOptions codeOptions, bool removeNullableBoolDefaults, bool dbContextOnly, bool entitiesOnly, bool useSchemaFolders) in C:/projects/efcorepowertools/src/GUI/RevEng.Core/ReverseEngineerScaffolder.cs:line 375
   at SavedModelFiles RevEng.Core.ReverseEngineerScaffolder.GenerateDbContext(ReverseEngineerCommandOptions options, List<string> schemas, string outputContextDir, string modelNamespace, string contextNamespace, string projectPath, string outputPath) in C:/projects/efcorepowertools/src/GUI/RevEng.Core/ReverseEngineerScaffolder.cs:line 102
   at ReverseEngineerResult RevEng.Core.ReverseEngineerRunner.GenerateFiles(ReverseEngineerCommandOptions options) in C:/projects/efcorepowertools/src/GUI/RevEng.Core/ReverseEngineerRunner.cs:line 88
   at async Task<int> EfReveng.Program.Main(string[] args) in C:/projects/efcorepowertools/src/GUI/efreveng/Program.cs:line 81

   at ReverseEngineerResult EFCorePowerTools.Handlers.ReverseEngineer.ResultDeserializer.BuildResult(string output)
   at async Task<ReverseEngineerResult> EFCorePowerTools.Handlers.ReverseEngineer.EfRevEngLauncher.GetOutputAsync()
   at async Task<ReverseEngineerResult> EFCorePowerTools.Handlers.ReverseEngineer.EfRevEngLauncher.LaunchExternalRunnerAsync(ReverseEngineerOptions options, CodeGenerationMode codeGenerationMode, Project project)
   at async Task EFCorePowerTools.Handlers.ReverseEngineer.ReverseEngineerHandler.GenerateFilesAsync(Project project, ReverseEngineerOptions options, string missingProviderPackage, bool onlyGenerate, List<NuGetPackage> packages, string referenceRenamingPath)
   at async Task EFCorePowerTools.Handlers.ReverseEngineer.ReverseEngineerHandler.ReverseEngineerCodeFirstAsync(Project project, string optionsPath, bool onlyGenerate, bool fromSqlProj)`

**E.g. output tt file > Run custom tool:**
![image](https://github.com/ErikEJ/EFCorePowerTools/assets/105279038/389f2605-6ff9-4057-bf9d-3ad073a6b130)

**Comment by ErikEJ** [comment]
@AchrWasUnavailable Please ask in the EF Core repo, it needs to be fixed there (or maybe even in VS)

**Comment by piskov** [comment]
I have two customizations in my own code. First one is `required` (which I see mentioned above, so I will not repeat it).

But I also have the code to avoid empty list allocations for collection navigations. So that we can go from this:
```
public ICollection<Item> Items { get; set;} = new List<Item>(); // wasted if collection was not included
```

…to this:
```
private ICollection<Item>? _items;  // sic! the nullable

public ICollection<Item> Items // not nullable but allocates an empty list only when needed (lazily)
{
    get => _items ??= new List<TestExample>();
    set => _items = value;
}
```

This is done with this quick hack (obviously copy-pasting 3 times the field name generation logic is a no-no)

```
#region Fields
<#

    foreach (var navigation in EntityType.GetNavigations())
    {
        var targetType = navigation.TargetEntityType.Name;
        if (navigation.IsCollection)
        {
#>
    private ICollection<<#= targetType #>>? _<#= navigation.Name[0].ToString().ToLower() + navigation.Name.Substring(1) #>;
<#
        }
    }
#>
    #endregion
```

… and inside properties loop:
```
#region Fields
<#

    foreach (var navigation in EntityType.GetNavigations())
    {
        var targetType = navigation.TargetEntityType.Name;
        if (navigation.IsCollection)
        {
#>
    private ICollection<<#= targetType #>>? _<#= navigation.Name[0].ToString().ToLower() + navigation.Name.Substring(1) #>;
<#
        }
    }
#>
    #endregion
```

**Comment by ErikEJ** [comment]
@piskov Thanks! Is this not "Custom Collection Initializers" from the list above?

**Comment by piskov** [comment]
@ErikEJ yeah, you’re absolutely right: to my shame, I’ve dismissed it due to “hashset” and “constructor” in the name and reinvented the wheel :-)

**Comment by ErikEJ** [comment]
@piskov no worries, your sample code is very valuable! 

I am comsidering at one point to create a "super" template where you can toggle these advanced options on.

**Comment by rajibsm** [comment]
Hi Erik, I see "INotifyPropertyChanged properties" in the checklist above. I am guessing this means the tool will be able to create model properties with property change notification. Any idea when this will be released? Thanks for all your hard work on this tool.

**Comment by piskov** [comment]
@rajibsm it’s really easy doing it yourself by customizing EntityType.t4 template.

For example to use ObservableCollection instead of list replace
```
if (navigation.IsCollection)
    {
#>
    public virtual ICollection<<#= targetType #>> <#= navigation.Name #> { get; set } =
        new List<<#= targetType #>>();
<#
    }
```
… with this
```
public virtual ICollection<<#= targetType #>> <#= navigation.Name #> { get; set } =
        new ObservableCollection<<#= targetType #>>();
```

Same goes for properties: you need to split them into fields + property declarations which is really easy if you use [my code](https://github.com/ErikEJ/EFCorePowerTools/issues/1499#issuecomment-1773937177) as a sample.

Both things should not take more than 30 minutes :-) It will probably not cover most of the EF cases but will do for your code (i. e. work correctly 95% of the time with some manual adjustments required later).

**Comment by ErikEJ** [comment]
@rajibsm This is currently just a list of customizations users have been asking for, with examples when available. As I mention [here](https://github.com/ErikEJ/EFCorePowerTools/issues/1499#issuecomment-1774129894), maybe one day I will consolidate in a "super" template.

**Comment by rajibsm** [comment]
@piskov Thank you for pointing me in the right direction. This was my first time editing T4 templates, but I was able to do it. Installing a T4 formatter extension for Visual Studio really helped to navigate the code template. @ErikEJ also has this helpful youtube [video ](https://www.youtube.com/watch?v=PUexkGWErNk) that will help with editing T4 templates.

**Comment by ErikEJ** [comment]
I have uploaded the start of a "Power" template, with the following features:

- Enum support
- Property renaming
- File header

https://github.com/ErikEJ/EFCorePowerTools/tree/master/samples/CodeTemplates/EFCore

**Comment by zoinkydoink** [comment]
I downloaded the templates mentioned above, but wasnt really sure what I needed to change to get the enum mapping support.
I think this feature should be controlled by the .json file you have and not template editing if possible.

Neverless, 
I have a entity called Activity and a property called ActivityType (int in db)
What changes would i need to make sure this property is a enum of type ActivityTypes after reverse engineering according to the table/template above? 

Thank you

**Comment by ErikEJ** [comment]
@zoinkydoink https://github.com/ErikEJ/EFCorePowerTools/issues/1472#issuecomment-1220273164

**Comment by rick1c** [comment]
Is it possible to have some (or maybe all) generated classes derive from a base entity?  i.e. add
 : BaseEntity 
to each class?

**Comment by ErikEJ** [comment]
@rick1c Yes, but it would go against Database First reverse engineering

**Comment by Pretagonist** [comment]
I'm  haveglobal usings and as such I don't need the using block in each entity file. But  even if I empty the usings variable it will still get a "using System:" line and it will take up space at the top of the entity file.

**Comment by ErikEJ** [comment]
@Pretagonist Please create an issue if you want help, this issue is closed
